INSERT INTO groups ( group_name) VALUES ('a2a2');
INSERT INTO groups ( group_name) VALUES ('b2b2');
INSERT INTO groups ( group_name) VALUES ('c2c2');
INSERT INTO groups ( group_name) VALUES ('d2d2');
INSERT INTO groups ( group_name) VALUES ('e2e2');
INSERT INTO groups ( group_name) VALUES ('f2f2');
INSERT INTO groups ( group_name) VALUES ('g2g2');
INSERT INTO groups ( group_name) VALUES ('k2k2');
INSERT INTO groups ( group_name) VALUES ('l2l2');
INSERT INTO groups ( group_name) VALUES ('m2m2');
INSERT INTO groups ( group_name) VALUES ('n2n2');
INSERT INTO groups ( group_name) VALUES ('o2o2');
INSERT INTO groups ( group_name) VALUES ('p2p2');
INSERT INTO groups ( group_name) VALUES ('q2q2');
INSERT INTO groups ( group_name) VALUES ('r2r2');
INSERT INTO groups ( group_name) VALUES ('s2s2');
INSERT INTO groups ( group_name) VALUES ('t2t2');
INSERT INTO groups ( group_name) VALUES ('u2u2');
INSERT INTO groups ( group_name) VALUES ('v2v2');
INSERT INTO groups ( group_name) VALUES ('x2x2');
INSERT INTO groups ( group_name) VALUES ('z2z2');
INSERT INTO groups ( group_name) VALUES ('w2w2');
INSERT INTO groups ( group_name) VALUES ('i2i2');
INSERT INTO groups ( group_name) VALUES ('j2j2');
INSERT INTO teachers (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '123', 'Peter', 'Petrov', '2020-09-03', 'webPP@mail.ru', 'MALE', 'City17');
INSERT INTO teachers (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '124', 'Ivan', 'Petrov', '2020-09-04', 'webIP@mail.ru', 'MALE', 'City18');
INSERT INTO teachers (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '125', 'Peter', 'Ivanov', '2020-09-05', 'webPI@mail.ru', 'MALE', 'City19');
INSERT INTO teachers (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '126', 'Peter', 'Smirnov', '2020-09-06', 'webPS@mail.ru', 'MALE', 'City17');
INSERT INTO teachers (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '227', 'Irina', 'Antonova', '2020-09-07', 'Antonova@mail.ru', 'FEMALE', 'City11');
INSERT INTO teachers (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '228', 'Olga', 'Voronina', '2019-09-07', 'Voronina@mail.ru', 'FEMALE', 'City1');
INSERT INTO teachers (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '229', 'Svetlana', 'Ulianova', '2020-09-07', 'Ulianova@mail.ru', 'FEMALE', 'City112');
INSERT INTO teachers (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '230', 'Ksenia', 'Gromova', '2018-09-07', 'Gromova@mail.ru', 'FEMALE', 'City11');
INSERT INTO teachers (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '231', 'Oksana', 'Petrova', '2020-04-07', 'PetrovaI@mail.ru', 'FEMALE', 'City14');
INSERT INTO teachers (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '232', 'Viktor', 'Yakovlev', '2001-01-01', 'Yakovlev@mail.ru', 'MALE', 'City11');
INSERT INTO teachers (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '233', 'Irina', 'Fedorova', '2012-09-07', 'Fedorova@mail.ru', 'FEMALE', 'City15');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '123', 'Peter', 'Petrov', '2020-09-03', 'webPP@mail.ru', 'MALE', 'City17');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '124', 'Ivan', 'Petrov', '2020-09-04', 'webIP@mail.ru', 'MALE', 'City18');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '125', 'Peter', 'Ivanov', '2020-09-05', 'webPI@mail.ru', 'MALE', 'City19');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '126', 'Peter', 'Smirnov', '2020-09-06', 'webPS@mail.ru', 'MALE', 'City17');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '227', 'Irina', 'Stepanova', '2020-09-07', 'Ivanov@mail.ru', 'FEMALE', 'City11');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '527', 'Daria', 'Ivanova', '2020-09-07', 'Ivanova@mail.ru', 'FEMALE', 'City20');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '528', 'Igor', 'Stepanov', '2020-09-07', 'Stepanov@mail.ru', 'MALE', 'City20');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '2123', 'Peter', 'Petrov', '2020-09-03', 'web2PP@mail.ru', 'MALE', 'City17');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '2124', 'Ivan', 'Petrov', '2020-09-04', 'web2IP@mail.ru', 'MALE', 'City18');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '2125', 'Peter', 'Zlobin', '2020-09-05', 'web2PI@mail.ru', 'MALE', 'City19');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '2126', 'Peter', 'Smirnov', '2020-09-06', 'web2PS@mail.ru', 'MALE', 'City17');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '2227', 'Yulia', 'Stepanova', '2020-09-07', 'Ivanov2@mail.ru', 'FEMALE', 'City11');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '2527', 'Daria', 'Ivanova', '2020-09-07', 'Ivanova2@mail.ru', 'FEMALE', 'City20');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '2528', 'Igor', 'Stepanov', '2020-09-07', 'Stepanov2@mail.ru', 'MALE', 'City20');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '3123', 'Peter', 'Petrov', '2020-09-03', 'web3PP@mail.ru', 'MALE', 'City17');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '3124', 'Alexander', 'Petrov', '2020-09-04', 'web3IP@mail.ru', 'MALE', 'City18');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '3125', 'Peter', 'Ivanov', '2020-09-05', 'web3PI@mail.ru', 'MALE', 'City19');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '3126', 'Peter', 'Anisimov', '2020-09-06', 'web3PS@mail.ru', 'MALE', 'City17');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '3227', 'Irina', 'Stepanova', '2020-09-07', 'Ivanov3@mail.ru', 'FEMALE', 'City11');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '3527', 'Daria', 'Ivanova', '2020-09-07', 'Ivanova3@mail.ru', 'FEMALE', 'City20');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '3528', 'Igor', 'Stepanov', '2020-09-07', 'Stepanov3@mail.ru', 'MALE', 'City20');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '32123', 'Peter', 'Petrov', '2020-09-03', 'web23PP@mail.ru', 'MALE', 'City17');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '32124', 'Ivan', 'Petrov', '2020-09-04', 'web23IP@mail.ru', 'MALE', 'City18');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '32125', 'Peter', 'Ivanov', '2020-09-05', 'web23PI@mail.ru', 'MALE', 'City19');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '32126', 'Peter', 'Smirnov', '2020-09-06', 'web23PS@mail.ru', 'MALE', 'City17');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '32227', 'Irina', 'Yran', '2020-09-07', 'Ivanov23@mail.ru', 'FEMALE', 'City11');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '32527', 'Zafira', 'Ivanova', '2020-09-07', 'Ivanova23@mail.ru', 'FEMALE', 'City20');
INSERT INTO students (personal_number, first_name, last_name, birthday, email, gender, address) VALUES ( '32528', 'Igor', 'Stepanov', '2020-09-07', 'Stepanov23@mail.ru', 'MALE', 'City20');
INSERT INTO courses (course_name, course_description) values ('Mathematics', 'Math');
INSERT INTO courses (course_name, course_description) values ('Biology', 'Bio');
INSERT INTO courses (course_name, course_description) values ('Chemistry', 'Chem');
INSERT INTO courses (course_name, course_description) values ('Physics', 'Phy');
INSERT INTO courses (course_name, course_description) values ('Informatica', 'Info');
INSERT INTO courses (course_name, course_description) values ('Philosophy', 'All about philosophy');
INSERT INTO courses (course_name, course_description) values ('Astronomy', 'All about astronomy');
INSERT INTO courses (course_name, course_description) values ('Geography', 'All about Geography');
INSERT INTO courses (course_name, course_description) values ('Physical education', 'All about physical education');
INSERT INTO courses (course_name, course_description) values ('History', 'All about history');
INSERT INTO courses (course_name, course_description) values ('Data structures and algorithms', 'All about Data structures and algorithms');
INSERT INTO courses (course_name, course_description) values ('Artificial intelligence', 'All about Artificial intelligence');
INSERT INTO courses (course_name, course_description) values ('Computer architecture and organisation', 'All about computer architecture and organisation');
INSERT INTO courses (course_name, course_description) values ('Computer networks', 'This branch of computer science aims to manage networks between computers worldwide');
INSERT INTO courses (course_name, course_description) values ('Databases and data mining', 'All about Databases and data mining');
INSERT INTO courses (course_name, course_description) values ('Computer graphics and visualization', 'Computer graphics is the study of digital visual contents and involves the synthesis and manipulation of image data. The study is connected to many other fields in computer science, including computer vision, image processing, and computational geometry, and is heavily applied in the fields of special effects and video games.');
INSERT INTO classrooms (classroom_address, classroom_capacity) values ('101', '50');
INSERT INTO classrooms (classroom_address, classroom_capacity) values ('102', '40');
INSERT INTO classrooms (classroom_address, classroom_capacity) values ('103', '30');
INSERT INTO classrooms (classroom_address, classroom_capacity) values ('104', '20');
INSERT INTO classrooms (classroom_address, classroom_capacity) values ('105', '50');
INSERT INTO classrooms (classroom_address, classroom_capacity) values ('106', '40');
INSERT INTO classrooms (classroom_address, classroom_capacity) values ('203', '30');
INSERT INTO classrooms (classroom_address, classroom_capacity) values ('204', '23');
INSERT INTO classrooms (classroom_address, classroom_capacity) values ('201', '50');
INSERT INTO classrooms (classroom_address, classroom_capacity) values ('202', '40');
INSERT INTO classrooms (classroom_address, classroom_capacity) values ('303', '30');
INSERT INTO classrooms (classroom_address, classroom_capacity) values ('304', '20');
INSERT INTO classrooms (classroom_address, classroom_capacity) values ('301', '55');
INSERT INTO classrooms (classroom_address, classroom_capacity) values ('402', '40');
INSERT INTO classrooms (classroom_address, classroom_capacity) values ('403', '30');
INSERT INTO classrooms (classroom_address, classroom_capacity) values ('504', '20');
INSERT INTO classrooms (classroom_address, classroom_capacity) values ('501', '50');
INSERT INTO classrooms (classroom_address, classroom_capacity) values ('602', '40');
INSERT INTO classrooms (classroom_address, classroom_capacity) values ('703', '30');
INSERT INTO classrooms (classroom_address, classroom_capacity) values ('704', '60');
INSERT INTO students_groups (student_id, group_id) values (1, 1);
INSERT INTO students_groups (student_id, group_id) values (2, 1);
INSERT INTO students_groups (student_id, group_id) values (3, 2);
INSERT INTO students_groups (student_id, group_id) values (4, 2);
INSERT INTO students_groups (student_id, group_id) values (5, 3);
INSERT INTO students_groups (student_id, group_id) values (6, 3);
INSERT INTO students_groups (student_id, group_id) values (7, 4);
INSERT INTO students_groups (student_id, group_id) values (8, 4);
INSERT INTO students_groups (student_id, group_id) values (9, 5);
INSERT INTO students_groups (student_id, group_id) values (10, 5);
INSERT INTO students_groups (student_id, group_id) values (11, 6);
INSERT INTO students_groups (student_id, group_id) values (12, 6);
INSERT INTO students_groups (student_id, group_id) values (13, 7);
INSERT INTO students_groups (student_id, group_id) values (14, 7);
INSERT INTO students_groups (student_id, group_id) values (15, 8);
INSERT INTO students_groups (student_id, group_id) values (16, 8);
INSERT INTO students_groups (student_id, group_id) values (17, 9);
INSERT INTO students_groups (student_id, group_id) values (18, 9);
INSERT INTO students_groups (student_id, group_id) values (19, 10);
INSERT INTO students_groups (student_id, group_id) values (20, 10);
INSERT INTO students_groups (student_id, group_id) values (21, 11);
INSERT INTO students_groups (student_id, group_id) values (22, 11);
INSERT INTO students_groups (student_id, group_id) values (23, 12);
INSERT INTO students_groups (student_id, group_id) values (24, 12);
INSERT INTO students_groups (student_id, group_id) values (25, 13);
INSERT INTO students_groups (student_id, group_id) values (26, 13);
INSERT INTO students_groups (student_id, group_id) values (27, 14);
INSERT INTO students_groups (student_id, group_id) values (28, 14);
INSERT INTO dailyschedule (dailyschedule_date) values ('2020-09-07');
INSERT INTO dailyschedule (dailyschedule_date) values ('2020-09-08');
INSERT INTO dailyschedule (dailyschedule_date) values ('2020-09-09');
INSERT INTO dailyschedule (dailyschedule_date) values ('2020-09-11');
INSERT INTO lectures (dailyschedule_id, local_time, course_id, classroom_id, group_id, teacher_id) values (1, '09:00:00', 1, 1, 2, 2);
INSERT INTO lectures (dailyschedule_id, local_time, course_id, classroom_id, group_id, teacher_id) values (1, '09:00:00', 1, 3, 4, 1);
INSERT INTO lectures (dailyschedule_id, local_time, course_id, classroom_id, group_id, teacher_id) values (1, '10:00:00', 2, 2, 2, 2);
INSERT INTO lectures (dailyschedule_id, local_time, course_id, classroom_id, group_id, teacher_id) values (1, '13:00:00', 2, 2, 3, 2);
INSERT INTO lectures (dailyschedule_id, local_time, course_id, classroom_id, group_id, teacher_id) values (1, '15:00:00', 4, 2, 3, 2);
INSERT INTO lectures (dailyschedule_id, local_time, course_id, classroom_id, group_id, teacher_id) values (2, '11:00:00', 3, 2, 2, 2);
INSERT INTO lectures (dailyschedule_id, local_time, course_id, classroom_id, group_id, teacher_id) values (2, '11:00:00', 2, 1, 3, 3);
INSERT INTO lectures (dailyschedule_id, local_time, course_id, classroom_id, group_id, teacher_id) values (3, '13:00:00', 2, 2, 3, 2);
INSERT INTO lectures (dailyschedule_id, local_time, course_id, classroom_id, group_id, teacher_id) values (3, '15:00:00', 4, 2, 3, 2);
INSERT INTO lectures (dailyschedule_id, local_time, course_id, classroom_id, group_id, teacher_id) values (4, '13:00:00', 2, 2, 3, 2);
INSERT INTO lectures (dailyschedule_id, local_time, course_id, classroom_id, group_id, teacher_id) values (4, '15:00:00', 4, 2, 3, 2);
INSERT INTO teachers_courses (teacher_id, course_id) values (1,1);
INSERT INTO teachers_courses (teacher_id, course_id) values (1,2);
INSERT INTO teachers_courses (teacher_id, course_id) values (1,3);
INSERT INTO teachers_courses (teacher_id, course_id) values (1,4);
INSERT INTO teachers_courses (teacher_id, course_id) values (2,1);
INSERT INTO teachers_courses (teacher_id, course_id) values (2,2);
INSERT INTO teachers_courses (teacher_id, course_id) values (2,3);
INSERT INTO teachers_courses (teacher_id, course_id) values (2,4);
INSERT INTO teachers_courses (teacher_id, course_id) values (3,1);
INSERT INTO teachers_courses (teacher_id, course_id) values (3,2);
INSERT INTO teachers_courses (teacher_id, course_id) values (3,3);
INSERT INTO teachers_courses (teacher_id, course_id) values (3,4);
INSERT INTO teachers_courses (teacher_id, course_id) values (4,1);
INSERT INTO teachers_courses (teacher_id, course_id) values (4,2);
INSERT INTO teachers_courses (teacher_id, course_id) values (4,3);
INSERT INTO teachers_courses (teacher_id, course_id) values (4,4);
INSERT INTO teachers_courses (teacher_id, course_id) values (5,1);
INSERT INTO teachers_courses (teacher_id, course_id) values (5,2);
INSERT INTO teachers_courses (teacher_id, course_id) values (5,3);
INSERT INTO teachers_courses (teacher_id, course_id) values (5,4);
INSERT INTO teachers_courses (teacher_id, course_id) values (6,1);
INSERT INTO teachers_courses (teacher_id, course_id) values (6,2);
INSERT INTO teachers_courses (teacher_id, course_id) values (6,3);
INSERT INTO teachers_courses (teacher_id, course_id) values (6,4);
INSERT INTO teachers_courses (teacher_id, course_id) values (7,1);
INSERT INTO teachers_courses (teacher_id, course_id) values (7,2);
INSERT INTO teachers_courses (teacher_id, course_id) values (7,3);
INSERT INTO teachers_courses (teacher_id, course_id) values (7,4);
INSERT INTO teachers_courses (teacher_id, course_id) values (8,1);
INSERT INTO teachers_courses (teacher_id, course_id) values (8,2);
INSERT INTO teachers_courses (teacher_id, course_id) values (8,3);
INSERT INTO teachers_courses (teacher_id, course_id) values (8,4);
INSERT INTO teachers_courses (teacher_id, course_id) values (9,1);
INSERT INTO teachers_courses (teacher_id, course_id) values (9,2);
INSERT INTO teachers_courses (teacher_id, course_id) values (9,3);
INSERT INTO teachers_courses (teacher_id, course_id) values (9,4);
INSERT INTO teachers_courses (teacher_id, course_id) values (10,1);
INSERT INTO teachers_courses (teacher_id, course_id) values (10,2);
INSERT INTO teachers_courses (teacher_id, course_id) values (10,3);
INSERT INTO teachers_courses (teacher_id, course_id) values (10,4);
INSERT INTO teachers_courses (teacher_id, course_id) values (11,1);
INSERT INTO teachers_courses (teacher_id, course_id) values (11,2);
INSERT INTO teachers_courses (teacher_id, course_id) values (11,3);
INSERT INTO teachers_courses (teacher_id, course_id) values (11,4);
INSERT INTO students_courses (student_id, course_id) values (1,1);
INSERT INTO students_courses (student_id, course_id) values (1,2);
INSERT INTO students_courses (student_id, course_id) values (1,3);
INSERT INTO students_courses (student_id, course_id) values (1,4);
INSERT INTO students_courses (student_id, course_id) values (1,5);
INSERT INTO students_courses (student_id, course_id) values (2,1);
INSERT INTO students_courses (student_id, course_id) values (2,2);
INSERT INTO students_courses (student_id, course_id) values (2,3);
INSERT INTO students_courses (student_id, course_id) values (2,4);
INSERT INTO students_courses (student_id, course_id) values (2,5);
INSERT INTO students_courses (student_id, course_id) values (3,1);
INSERT INTO students_courses (student_id, course_id) values (3,2);
INSERT INTO students_courses (student_id, course_id) values (3,3);
INSERT INTO students_courses (student_id, course_id) values (3,4);
INSERT INTO students_courses (student_id, course_id) values (3,5);
INSERT INTO students_courses (student_id, course_id) values (4,1);
INSERT INTO students_courses (student_id, course_id) values (4,2);
INSERT INTO students_courses (student_id, course_id) values (4,3);
INSERT INTO students_courses (student_id, course_id) values (4,4);
INSERT INTO students_courses (student_id, course_id) values (4,5);
INSERT INTO students_courses (student_id, course_id) values (5,1);
INSERT INTO students_courses (student_id, course_id) values (5,2);
INSERT INTO students_courses (student_id, course_id) values (5,3);
INSERT INTO students_courses (student_id, course_id) values (5,4);
INSERT INTO students_courses (student_id, course_id) values (5,5);
INSERT INTO students_courses (student_id, course_id) values (6,1);
INSERT INTO students_courses (student_id, course_id) values (6,2);
INSERT INTO students_courses (student_id, course_id) values (6,3);
INSERT INTO students_courses (student_id, course_id) values (6,4);
INSERT INTO students_courses (student_id, course_id) values (6,5);
INSERT INTO students_courses (student_id, course_id) values (7,1);
INSERT INTO students_courses (student_id, course_id) values (7,2);
INSERT INTO students_courses (student_id, course_id) values (7,3);
INSERT INTO students_courses (student_id, course_id) values (7,4);
INSERT INTO students_courses (student_id, course_id) values (7,5);
INSERT INTO students_courses (student_id, course_id) values (8,1);
INSERT INTO students_courses (student_id, course_id) values (8,2);
INSERT INTO students_courses (student_id, course_id) values (8,3);
INSERT INTO students_courses (student_id, course_id) values (8,4);
INSERT INTO students_courses (student_id, course_id) values (8,5);
INSERT INTO students_courses (student_id, course_id) values (9,1);
INSERT INTO students_courses (student_id, course_id) values (9,2);
INSERT INTO students_courses (student_id, course_id) values (9,3);
INSERT INTO students_courses (student_id, course_id) values (9,4);
INSERT INTO students_courses (student_id, course_id) values (9,5);
INSERT INTO students_courses (student_id, course_id) values (10,1);
INSERT INTO students_courses (student_id, course_id) values (10,2);
INSERT INTO students_courses (student_id, course_id) values (10,3);
INSERT INTO students_courses (student_id, course_id) values (10,4);
INSERT INTO students_courses (student_id, course_id) values (10,5);